### ISSUE TITLE
`pop` instead of `pilfer`

### ISSUE THREAD

**Issue by ecatmur** [SebastienBini/cpp-relocation-proposal#12]
Could we use `pop` instead of `pilfer` (and `pop_front`, `pop_back` etc.)? Is this an ABI compatibility issue?

**Comment by ecatmur** [comment]
Aha. From https://wg21.link/P0084 (which introduced `emplace_back` returning by reference):

> ### ABI Breakage
> When this paper was discussed by the LEWG in Kona (October 2015), there was general approval
of the concept, but there was a concern raised by Jonathan Wakely that it would break ABI for
C++17. This resulted in the paper being rejected. I have discussed this with Jon and he believes
he was mistaken—this change is to a template and return types are part of the mangled name
for templates, therefore this will not break ABI.
> ### Performance
> A question was raised in Kona about the performance effects of this change. Howard Hinnant did
a small test with one compiler and there was no code generated for a return type if the return
value was not used. I take this as good evidence that there will be no performance implications.

**Comment by SebastienBini** [comment]
Nice find! 

Okay for the ABI point. But I am not sure the performance point applies in this case. Consider a possible std::vector pilfer_back/pop_back implementation:
```c++
T vector<T>::pop_back()
{
  return std::destroy_relocate(--_end);
}
```
This looks more complex to optimize than in emplace_back. I'd be pleasantly surprised if the compiler can generate code where `std::destroy_relocate` gets turned into a mere `std::destroy_at` if the return value is not used. I guess we should make some tests if we want to propose the 'pop' version.

If there are no ABI breaks, and no performance hits, I'm in favor of reusing 'pop' as well.

**Comment by SebastienBini** [comment]
Actually, discarded `std::destroy_relocate` expressions are quite similar to discarded reloc expressions.
I don't know to what extends we can mandate that discarded `std::destroy_relocate` be turned into `std::destroy_at`. 

If this is ensured somehow, then it will likely have no performance hit when the return value is not needed.

**Comment by ecatmur** [comment]
Test bed:

```c++
#pragma GCC optimize ("O1")

#include <array>
#include <cstring>
#include <memory>
#include <string>
#include <utility>
#include <vector>

template<class T>
[[gnu::always_inline]] T pilfer_back(std::vector<T>& v) {
    auto& b = *--((T**)&v)[1];
    T x = std::move(b);
    b.~T();
    return x;
}

#ifdef PILFER
#define X(...) void f(std::vector<__VA_ARGS__>& v) { pilfer_back(v); }
#else
#define X(...) void f(std::vector<__VA_ARGS__>& v) { v.pop_back(); }
#endif

struct S {
    S() {}
    S(S&& rhs) { std::memmove(this, &rhs, sizeof *this); }
    void* data[3];
};

X(int)
X(std::array<int, 1024>)
X(S)
X(std::unique_ptr<int>);
X(std::shared_ptr<int>);
X(std::string)
```

Diff view: https://diff.godbolt.org/z/q37x1h67q

At O1 and above, gcc optimizes everything except `f(std::string)` to **identical** codegen. At Og and below, unfortunately, it's not so good - but how much does this really matter? This might be a question for SG14 since AFAIA non-optimized performance is really only a concern for games programmers. IMO avoiding bloating the API might well be worth it.

Also this is only with synthesized relocation, so relocation constructors could well improve the situation, as could relocation elision.

> I don't know to what extent we can mandate that discarded std::destroy_relocate be turned into std::destroy_at.

I don't think we can mandate it, but we can certainly permit it via elision.

I'll turn this thread into a discussion section.

**Comment by SebastienBini** [comment]
That's quite interesting. clang 15 (-O2) does generate different code also for unique_ptr and shared_ptr.

However the move and destructor call are two separate operations, while it's only one operation with relocation. We will have to check that the relocation ctor call is indeed optimized into a destructor call. But this is encouraging.

Any idea why std::string couldn't benefit from the same optimization in your example?

> IMO avoiding bloating the API might well be worth it.

We may have to consider that developers may not know about this optimization, and they may treat this new return type as a downgrade (performance hit).

> I don't think we can mandate it, but we can certainly permit it via elision.

It might be worth adding a note to the discarded reloc expression section.

**Comment by ecatmur** [comment]
> Any idea why std::string couldn't benefit from the same optimization in your example?

Not really; it might be SSO weirdness.

> We may have to consider that developers may not know about this optimization, and they may treat this new return type as a downgrade (performance hit).

Yes. OTOH it may not be noticeable, particularly once the performance improvements of relocation are taken into account.

There is one more issue, which is that `pop_back()` may not return a value if `T` is non-relocatable. It is possible to create a vector of such objects, if they are default-constructible, and much easier with node-based containers. So `pop_back()` would need a conditional result type. Perhaps `pop_back(std::relocate)` would be better.

**Comment by SebastienBini** [comment]
> There is one more issue, which is that `pop_back()` may not return a value if `T` is non-relocatable. It is possible to create a vector of such objects, if they are default-constructible, and much easier with node-based containers. So `pop_back()` would need a conditional result type. Perhaps `pop_back(std::relocate)` would be better.

Damn, indeed, there are such cases. So it must be `pop(std::relocate)` or `pilfer`, no strong opinion one way or the other. Actually both alternatives can be proposed.
