### ISSUE TITLE
Relocation from data-members if *this is a prvalue

### ISSUE THREAD

**Issue by SebastienBini** [SebastienBini/cpp-relocation-proposal#20]
#18 makes me think of an aspect we hadn't considered so far, and might allow us to get rid of `std::decompose`. `reloc` can only be used on function-local variables, and hence, not on data members. But what if the class is a prvalue? 

Maybe we could allow, under some conditions, to relocate from data-members if *this is a prvalue.

```c++
class T
{
public:
  auto get_all(this T self) { return std::tuple{std::relocate, reloc self.name, reloc self.tp}; }

private:
  std::string name;
  RelocOnly tp;
};
```

We could restrict this with the same restrictions that apply on `std::decompose`. However I see two problems:

1. With deducing this, we cannot just use the name of the data members, as they need to be accessed by the `self` object, hence violating the rule that reloc must only be applied to variables. We could fix this with a new kind of overload:
```c++
class T
{
public:
  auto get_all() = /* '=' or another symbol to indicate that *this is a prvalue, similar to '&' and '&&' */
  { return std::tuple{std::relocate, reloc name, reloc tp}; }
// ...
};
```
If this approach is followed, then we ensure that only the class member functions can relocate their data-members, (even friends could not).

2. We cannot easily relocate base classes as they don't have a variable to hold their name. But we could allow `reloc base-class-type;`.

```c++
class Derived : public T
{
public:
  auto get_all() =
  {
    auto t = reloc T; /* relocates the T base class into t */
    /* `name` and `tp` can no longer be used (ill-formed) as they belong to T which was relocated. */
    return (reloc t).get_all(); /* forward */
  }
private:
};
```

If we have both points, then we can most likely remove `std::decompose` and we have more flexible relocation rules.

**Comment by ecatmur** [comment]
Oh, I like it.

1. Maybe `auto get_all(this T reloc) { ... }`? Or even `auto get_all(reloc this T)`? It'd be advisable to have a syntax that prevents naming the "self" object, since said object's lifetime has already ended so naming it is pointless and error-prone. Also we need to emphasize that the destructor has *not* been invoked.
2. Hopefully, yeah. `sizeof` and `typeid` are many-kinded, so it's possible in the syntax to have an operator that takes both types and expressions. However both take a parenthesized type (`typeid` also a parenthesized expression) - I'm not sure why.

I don't think you should be able to name base class data members at all; otherwise there's a lot of special casing (you can't `reloc` them, can't name them after `reloc`ing the base class). Instead I think if you want to access them you have to use `reloc` to bind a name to the base (i.e. `auto T = reloc T; t.name; ` above).

**Comment by SebastienBini** [comment]
Hmm. One way to allow this is to state that a function with `reloc this T` as parameter would decompose the object from the start:

- `this` is inaccessible in the function body ;
- Upon calling the function, before the function body is entered, `*this` is decomposed into individual objects for each direct base and data member. This decomposition is a no-op: each subobject of `*this` merely gets considered as a complete object ;
- The destructor of the source object is never called ;
- The direct base objects have no identifiers, and can only be accessed once through the `reloc Base` (or `reloc(Base)`) expression ;
- The data member objects can be accessed normally (except that they are complete objects now) ;

A few concerns or points to clarify:

- what about anonymous unions or overlapping base classes? `reloc this T` functions could be ill-formed, or the overlapping objects made inaccessible or unrelocatable?
- How is the `this` parameter passed in terms of ABI? Is there some form of eliding/aliasing?
- this construct may be dangerous as it elides the destructor call. Misinformed users may create leaks. And the code looks a bit weird:

```c++
T* unique_ptr<T>::release(reloc this unique_ptr)
{
  // no dtor is called on the source object, the "owned" pointer is loose at this point.
  return _ptr;
}
```

It could still work with templates, and hence it can be done on lambdas as well:
```c++
RelocOnly x;
auto const func = [y = reloc x](reloc this auto)
{
  foo(reloc y);
};
(reloc func)();
```

**Comment by ecatmur** [comment]
> * what about anonymous unions or overlapping base classes? `reloc this T` functions could be ill-formed, or the overlapping objects made inaccessible or unrelocatable?

Anonymous unions - I would like to just allow those. The names of union members would have to act as aliases, and it would be up to the programmer to be careful with them. That's fine; unions have sharp edges anyway.
EBO bases and [[no_unique_address]] members - I don't see any reason to disallow these. They can be observed to overlap during cdestruction [class.cdtor] anyway.
Virtual bases (and bases with virtual bases) - unrelocatable, or ill-formed. I think the former should be fine.

> * How is the `this` parameter passed in terms of ABI? Is there some form of eliding/aliasing?

It's already a prvalue before the call, so the relocating member function operates in-place. The relocation in `(reloc ptr).release()` is elidable.

> * this construct may be dangerous as it elides the destructor call. Misinformed users may create leaks. And the code looks a bit weird:

It has to walk a fine line, yeah - ugly enough to make users cautious without scaring them off entirely.

**Comment by SebastienBini** [comment]
Okay, works for me. So if we agree on that, I'll submit a PR to:

- introduce a new section about "decomposing functions" (that take `reloc this T`) as parameter.
- remove `std::decompose`.
- hint that `get_all` will likely need to be implemented as a "decomposing function".

**Comment by ecatmur** [comment]
Just thinking again about ABI - we want to be able to form a pointer to a decomposing/relocating member function, so (as with any explicit object member function) the ABI must be that of a function taking a prvalue of the class type in first position. For example, the type of `&unique_ptr<int>::release` is simply `int (*)(unique_ptr<int>)`. This means that we have the same caller-destroy problem as usual. I don't think this is a showstopper, though.

**Comment by SebastienBini** [comment]
Hmm, true. However, I believe we can proceed as with the assignment operator, emitting two functions. The non-eliding one will make a temporary (if caller-destroy) and call the eliding one.

This requires the type to have at least a copy, move or relocation constructor. I think it's acceptable. In #15 we stated that using `reloc` on a value parameter that has none of the three constructors is ill-formed. So requiring the same for decomposing functions is consistent.

Does `reloc this T` need to appear on the declaration or only in the definition? If we mandate it to appear in the declaration (which seems more natural to me) then all consumers of the class may directly call the eliding function.

**Comment by ecatmur** [comment]
The caller doesn't *need* to know that a (pvalue explicit object) member function is decomposing; it's just an optimization (and only that under certain, possibly hypothetical circumstances). So I would make it optional on a declaration and mandatory on a definition.

For example, you could write a member function `A::release(reloc this A) { ... }` and later decide to refactor, making it a non-decomposing mfcn forwarding to a decomposing private impl: `A::release(this A self) { return releaseImpl(reloc self); }`. If `reloc this T` were mandatory on the declaration this would be an ABI break.

**Comment by SebastienBini** [comment]
Yes I agree that's a definition detail, and the caller does not need to know.

However it feels weird to have a "qualifier" around a parameter in the definition( `reloc this T`) and not in the declaration `this T`. Users may not think that the definition matches the declaration. I don't think it's a blocking issue, but that's why I rose the point in the first place.

What's your stance on emitting the two functions like what is done for the assignment operator?

**Comment by ecatmur** [comment]
OK, in that case let's go back to `this T reloc`. It's well-known that a *declarator* can be omitted in a *parameter-declaration* in a function declaration that is not a definition, so that won't feel as weird.

Emitting two functions is fine as an implementation detail, but we can't mandate it because there isn't any compiler-generated code calling these functions.

**Comment by SebastienBini** [comment]
> OK, in that case let's go back to `this T reloc`. It's well-known that a _declarator_ can be omitted in a _parameter-declaration_ in a function declaration that is not a definition, so that won't feel as weird.

Fine by me.

> Emitting two functions is fine as an implementation detail, but we can't mandate it because there isn't any compiler-generated code calling these functions.

It's not clear to me but at least I can start writing the section.

**Comment by ecatmur** [comment]
> It's not clear to me but at least I can start writing the section.

Maybe we can do this; the question is how to mandate it in a way that is meaningful, implementable and effective.

We mandate elision in `operator=` by saying (something like) that given a subobject of class type having qualifying relocation constructor and qualifying relocation assignment operator, the defaulted `operator=` of the containing class type does not odr-use any copy, move or relocation constructor of the subobject class type.

So let's say that given a prvalue explicit object member function that either is *declared* with explicit object parameter `this T reloc`, *or* whose class type has a qualifying relocation constructor, a member function call expression that invokes that member function (which will be by name, not via a function pointer) on (i.e. having object expression) a prvalue of that class type (possibly cv-qualified) does not odr-use any copy, move or relocation constructor of the class type.

This will force the implementation to shadow any caller-destroy (non-eliding) symbol with a callee-destroy (eliding) variant, while allowing them to keep ABI for function pointers - I think that should work.

**Comment by SebastienBini** [comment]
Thanks for your input. I should be able to start writing.

**Comment by SebastienBini** [comment]
Hey,

I've updated the PR to better support CRTP, but I still see some minor issues with decomposing functions:

1. In the case of a template decomposing function, naming the data member directly may be tricky to parse:

```c++
struct GetFirst {
template <class T>
auto get_first(this T reloc) { return first; }
}; 
```

What does `first` refer to, when it comes to parse the function body for the first time? Usually we can disambiguate with `this->first` but `this` is not accessible here. I guess `auto get_first(this T reloc) { return T::first; }` should be possible as it is today. But this implies that the following must be valid as well:
```c++
struct GetFirst {
template <class T>
void fwd(this T reloc) { foo(reloc T::first /* no longer a mere variable name */); }
};
```

But it should be fine IMO.

2. Again, in the case of a template decomposing function, what do we do with inaccessible data members?

```c++
struct GetPair {
template <class T>
auto get_pair(this T reloc) { return std::pair{reloc T::first, reloc T::second}; } 
};

class WeirdPair : public GetPair
{
public:
  int first;
private:
  int second;
};

// how does get_pair(WeirdPair{}) behave, if even well-formed, 
// given that `second` is inaccessible with regards to `GetPair`?
```

My take is that inaccessible subobjects are simply destructed when the function leaves and cannot be accessed in the function body. Hence `get_pair(WeirdPair{}) ` is ill-formed, but well-formed with an `std::pair`.

3. How to make decomposing functions work with data-member address? This is more of a syntax problem.

```c++
template <auto FirstAddr, auto SecondAddr>
struct GetPair {
template <class T>
auto get_first(this T const& self) { return self.*FirstAddr; } 
template <class T>
auto get_pair(this T reloc) { return std::pair{/* reloc *FirstAddr, reloc *SecondAddr ??? */}; } 
};
```

I have no clue here for the moment.

Now that I am thinking about it, I am not so sure we would want to allow it altogether, become then what happens if a parameter, referred to by name, is passed to `reloc`, and a another parameter, referred to by a data-member address known at compile time, is passed to `reloc`? Does the compiler check that the data-member address points to a different member than the first one? What about runtime addresses?

```c++
template <auto FirstAddr>
struct GetPair {
template <class T>
auto get_pair(this T reloc) { return std::pair{reloc *FirstAddr, reloc T::second}; }
// What happens if FirstAddr mistakenly points to `&T::second`?
};
```

I believe it's safer to rule them out for the moment.

4. How to make a decomposing lambda compound usable?

By a lambda compound I mean the set of lambda overloads we build when using variants (see `overloaded` definition [here](https://en.cppreference.com/w/cpp/utility/variant/visit)).

```c++
auto compound = overloaded(
  [r = get_reloc_only()](this auto reloc, int) { return r /* <- ill-formed */; },
  [](this auto, auto) { throw std::runtime_error{"internal error"}; }
);
auto r = std::visit(reloc compound, std::variant<int, std::string>{});;
```
This will not compile as the first lambda parameter type is the `overloaded` structure, and hence `r` is inaccessible as it is a data-member of a parent class.

I don't know if that's a blocking issue though, I believe it would be quite rare to encounter such cases...

**Comment by SebastienBini** [comment]
For point 2, I believe the decomposition function definition should be ill-formed if there is any inacessible subobject from the decomposing function (same requirement we have in #23), as we will be calling their destructor when the function exits. I'll update the PR in that regards.
