### ISSUE TITLE
Paper number and title

### ISSUE THREAD

**Issue by ecatmur** [SebastienBini/cpp-relocation-proposal#22]
I'm about to reserve a paper number on the isocpp system so that we can talk about it with a concrete identifier. This is the first step towards publication - but don't worry, I'm not going to publish it until we agree that it's ready!

However, the isocpp system is asking for a paper title and I don't particularly like the current "prvalue relocation" - it's a bit too terse compared to typical paper titles (see https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/ for the current mailings). It's possible to change a paper title on the system, at least up until publication, but it'd be good to get a good title in place from the start. Any ideas?

**Comment by SebastienBini** [comment]
Nice! A few ideas on top of my head:

- Relocate-only types and trivial relocation ;
- (Support for) Relocation in the existing type system ;
- Trivial and non-trivial relocation ;

I'll post new names as I have new ideas. I like the second one best for the moment.

**Comment by SebastienBini** [comment]
Thanks, but do you know how we can refresh the contents of https://isocpp.org/files/papers/D2785R0.html ? Unless it redirects to github review?
