### ISSUE TITLE
Synthesized relocation and defaulted relocation constructor

### ISSUE THREAD

**Issue by ecatmur** [SebastienBini/cpp-relocation-proposal#8]
You write:

> Alternatively, if synthesized relocation should happen for all subobjects of T and that T provides a move constructor, then the relocation constructor delegates to the move constructor and calls its destructor on the source object right after.

I don't agree with this; the behavior should be predictable. If you want relocation of T to perform move-and-destroy, just don't declare a relocating constructor at all.

**Comment by SebastienBini** [comment]
Hmm, indeed. I think we can remove that part.
